### ISSUE TITLE
Failed to find module 'nativescript-social-share'

### ISSUE THREAD

**Issue by jvzanatta** [tjvantoll/nativescript-social-share#11]
Got the error from the title above. I followed the [Nativescript tutorial](http://docs.nativescript.org/angular/tutorial/ng-chapter-5.html) step by step and even took a look at the plugin readme, and I was sure I did everything right. So I opened the package.json and found ` "main": "social-share.js",`, then copied the android file **social-share.android.js** and renamed it to **social-share.js**, now the error is gone. Based on that i believe the problem is with the framework "redirecting" to the right platform file. How can I solve that? 

Thanks in advance, awesome plugin!

**Comment by tjvantoll** [comment]
Hey @jvzanatta,

And hmmm... that’s odd. The way this is _supposed_ to work, is the NativeScript CLI will rename `social-share.android.js` to `social-share.js` when it puts the file in `platforms/android`.

Can you paste in the error you’re getting here? That might help me figure out what’s up here.

Thanks.

**Comment by jvzanatta** [comment]
After I deleted both `platforms `and `node_modules`, and also the content of `hooks/after-prepare`, the error is gone :/ i wish i had printed my screen when it happened. I also executed tns install instead of npm install. Dunno which affected the plugin. 

Thanks once more and keep the great work!

**Comment by tjvantoll** [comment]
Glad to hear you got this working! And thanks 😄
