### ISSUE TITLE
Does not work with custom modal nativescript angular2

### ISSUE THREAD

**Issue by mourice** [tjvantoll/nativescript-social-share#20]
I tried opening the share dialog from Modal page [https://docs.nativescript.org/angular/ui/dialogs.html#custom-dialog] and got the below error.

**`Attempt to present <UIActivityViewController: 0x15be1d60> on <UINavigationController: 0x14608e80> whose view is not in the window hierarchy!`**

Issue with the ios platform not tested on android

**Comment by skxc-tech** [comment]
Confirming, just encountered this bug on iOS.
