### ISSUE TITLE
Share text on Facebook

### ISSUE THREAD

**Issue by d3mac123** [tjvantoll/nativescript-social-share#22]
Hi, I'm trying the plugin and I noticed the shareText (haven't tried the shareImage yet) does not add the text when I select Facebook (text comes perfectly for Whatsup, Twitter, Messaging, etc). The FB simply goes blank.

Anything am I doing wrong?

**Comment by preethijayanthi** [comment]
I also have the same issue. The text is not adding and FB goes blank

**Comment by EddyVerbruggen** [comment]
That's per Facebook-design. Nothing you can do about that. They want the user to make up their own story instead of having the app prefill something.

**Comment by preethijayanthi** [comment]
But How in IOS, Its working fine.
