### ISSUE TITLE
Image Sharing Issues

### ISSUE THREAD

**Issue by URvesh109** [tjvantoll/nativescript-social-share#23]
import { ImageSource } from "image-source";

let image =  ImageSource.fromFile("~/path/to/myImage.jpg");

[ts] Property 'fromFile' does not exist on type 'typeof ImageSource'.

**Comment by EddyVerbruggen** [comment]
That's not actually related to this plugin..

`fromFile` is not a static function so you can't invoke it on the type. You need to instantiate a class instead:

```typescript
      let img = new ImageSource();
      if (img.loadFromFile("~/path/to/myImage.jpg")) {
        // do something with img
      }
```
