### ISSUE TITLE
Image sharing doesn’t work in Android API level 23

### ISSUE THREAD

**Issue by tjvantoll** [tjvantoll/nativescript-social-share#3]
On Android 6.0 image sharing doesn’t work because of Android 6’s new permission model. See https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/438 for a more detailed discussion.

**Comment by raefa** [comment]
For now I'm disabling social share on Android. @tjvantoll do you know of another plugin that deals with the new permissions nicely? If I get around to it I will try and patch (my Android is limited).

**Comment by tjvantoll** [comment]
@raefa Unfortunately I’m not aware of any :( If you have any success let me know. I’ve been trying to find some time to dig into this one myself.

**Comment by f-marquez** [comment]
I have added a new function to "social-share.android.js" to pass the image path and name instead of an image object. I hope it is useful for you too.

```
shareImagePath: function(imgPath, imgName, subject) {
		var intent = getIntent("image/jpeg");
		
		var newFile = new java.io.File(imgPath, imgName);

		intent.putExtra(android.content.Intent.EXTRA_STREAM,
			android.net.Uri.fromFile(newFile));

		share(intent, subject);
	}
```

To call it use
`socialShare.shareImagePath("/path/to/image", "imageFileName.jpg");`

**Comment by dkallkro** [comment]
Hi, we seems to have fixed it by changing this line:

Line 29 or something in the social-share.android.js
from:
var newFile = new java.io.File(context.getExternalFilesDir(null), imageFileName);
To:
var newFile = new java.io.File(application.android.context.getExternalFilesDir(null), imageFileName);

**Comment by pattrawuth2530** [comment]
Image sharing doesn't work in Android X (API level 29)
