### ISSUE TITLE
Link With Text share on facebook

### ISSUE THREAD

**Issue by anaszgh** [tjvantoll/nativescript-social-share#36]
Hello, 

I'm using TNS@4.0.1 and whenever i try to share a link with text to facebook, the link appears but the text doesn't

here is the implementation.
```
socialShare.shareUrl("google.com",`I have scored ${this.best} can you beat this achievement??!!`,"High Score");
```

**Comment by EddyVerbruggen** [comment]
It’s Facebook policy to have the user write something - it can’t be prefilled.
