### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by x4080** [tjvantoll/nativescript-social-share#4]
Hi, Im trying with ios 9 simulator xcode 7.01 and ios 8 iphone 4s to share text to mail, and after mail displayed, it crashed, just calling socialShare.shareText("I love NativeScript!"); no I love Nativescript in the mail app too, just empty text

Is it just me ?

Edit:Share to copy text is working fine
Edit:In device now its working, simulator still crashes (weird) :)

**Comment by tjvantoll** [comment]
Hey @x4080,

Sorry for the late response. Yeah this is a known thing that if you don’t have any email accounts setup on the iOS simulator it’ll just crash.

This shouldn’t be related to the plugin at all. If you try this on a physical device it should work. If you run into any other issues let me know.
