### ISSUE TITLE
Share text is empty for Facebook channel on Android

### ISSUE THREAD

**Issue by guillaume-roy** [tjvantoll/nativescript-social-share#6]
I want to share a text on the Facebook app but the text is empty when the app is loaded.
I tested on a physical device which has Android 5.1 installed.

* tns-android 1.6.3
* tns-core-modules 1.6.0
* nativescript-social-share ^1.1.2

**Comment by guillaume-roy** [comment]
I have the same issue on : 

* tns-android 1.7.1
* tns-core-modules 1.7.1

**Comment by tjvantoll** [comment]
Hey @guillaume-roy,

Sorry I let this sit for so long. I can recreate this problem but I’m not sure what’s up. I think I might need @eddyverbruggen’s expertise 😀

**Comment by tjvantoll** [comment]
From @eddyverbruggen, who for some strange reason is unable to comment here:

> This is the cause of many tickets in the Cordova sister plugin. Check for instance [this issue](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/344) - it's against Facebook's policy to prefill the sharesheet message.

**Comment by guillaume-roy** [comment]
Yeah i found that this morning. It seems that only URLs are authorized to share message.
Bad Facebook bad :s

**Comment by EddyVerbruggen** [comment]
Facebook stinks (testing if TJ unblocked me) :+1:

**Comment by poorcoder** [comment]
Hi All,
I found this repo. This is working very well...
https://github.com/mobilemindtec/nativescript-facebook
