### ISSUE TITLE
Cannot install nativescript-social-share

### ISSUE THREAD

**Issue by NMNiOS** [tjvantoll/nativescript-social-share#7]
Unable to install plugin, getting this error **"-bash: Regards,tns: command not found"**  Please help me to get it installed.

![screen shot 2016-04-25 at 4 47 39 pm](https://cloud.githubusercontent.com/assets/18345960/14783622/7d1f074c-0b0e-11e6-9b1a-b514c831a17c.png)

**Comment by tjvantoll** [comment]
Hey @NMNiOS,

The problem here is you don’t have the NativeScript CLI installed. Go through the [NativeScript CLI installation instructions](https://docs.nativescript.org/start/quick-setup#the-nativescript-cli) and you should be good to go.

**Comment by NMNiOS** [comment]
Even after the installation the same issue exists...

**Comment by tjvantoll** [comment]
Hmmm... there might be an issue with your Node.js or npm installation then. What do you get from `node --version` and `npm --version`?
